#!/bin/bash
CONFIG_FILE="$HOME/.bashrc"
if [ "$1" == "-r" ]; then
    # Remove alias mode
    if [ $# -ne 2 ]; then
        echo "Usage: alas -r <alias_name>"
        exit 1
    fi
    ALIAS_NAME=$2
    # Remove the alias from the file
    sed -i "/alias $ALIAS_NAME=/d" "$CONFIG_FILE"
else
    # Add alias mode
    if [ $# -ne 2 ]; then
        echo "Usage: alas <alias_name> <command>"
        exit 1
    fi
    ALIAS_NAME=$1
    COMMAND=$2
    # Add the alias to file
    echo "alias $ALIAS_NAME='$COMMAND'" >> "$CONFIG_FILE"
fi
